name: "✨ Add a new Theme"
description: >
  Do you have a fancy theme that is not listed yet?

title: "Add Theme <theme>"
labels: theme

body:
  - type: markdown
    attributes:
      value: "> Thank you so much for your help to make this list even better! 💖"
      
  - type: input
    id: theme-website
    attributes:
      label: Theme Repository
      description: Link to the project (e.g. GitHub)
      placeholder: ex. https://github.com/awesome-jellyfin/awesome-jellyfin
    validations:
      required: true
      
  - type: textarea
    id: theme-images
    attributes:
      label: Theme Preview
      description: Add some images of the theme
    validations:
      required: true
