name: "✨ Request something else"
description: >
  Do you have anything else that is not yet listed and want it to be listed in the repo?

title: "Add <project>"
labels: 
  - request

body:
  - type: markdown
    attributes:
      value: |
        > Thank you so much for your help to make this list even better! 💖"
      
  - type: input
    id: project-website
    attributes:
      label: Project Website
      description: Link to the project (e.g. GitHub)
      placeholder: ex. https://github.com/awesome-jellyfin/awesome-jellyfin
    validations:
      required: true
      
  - type: textarea
    id: project-description
    attributes:
      label: Project Description
      description: Description of the project
    validations:
      required: true

  - type: input
    id: short-description
    attributes:
      label: Short Description
      description: |
        This description will be shown in the list. 
        It should be:
        * neutral
        * 1 (max 2) sentence(s) long
        * shouldn't contain technologies (e.g. `Built with Python`)
        * use proper capitalization (e.g. `Jellyfin` instead of `jellyfin`)
        * start with a capital letter and end with a `.`
    
  - type: textarea
    id: other
    attributes:
      label: Anything else?
