name: "🚩 Report a mistake (e. g. Spelling, Grammar, ...)"
description: >
  Did you find an error in the list?

labels: bug

body:
  - type: markdown
    attributes:
      value: "> Thank you so much for your help to make this list even better! 💖"
      
  - type: textarea
    id: what-problem
    attributes:
      label: "What's the problem?"
      description: Briefly describe the error / suggest changes
      placeholder: "wrote 'Jelyfin' instead of 'Jellyfin'"
    validations:
      required: true
      
  - type: input
    id: where-problem
    attributes:
      label: "Where's the problem?"
      description: Line Number of the problem
      placeholder: "ex. https://github.com/awesome-jellyfin/awesome-jellyfin/blob/main/README.md?plain=1#L20"
    validations:
      required: true
    
  - type: markdown
    attributes:
      value: |
        > Please enter the Line Number of the problem to make it easier for us to find the problem. 
        > You can find the line numbers [here](https://github.com/awesome-jellyfin/awesome-jellyfin/blob/main/README.md?plain=1). You can click on the line numbers to get the URL for the clicked line.