name: "ðŸ” Report a project (e. g. Inactive, Broken, Harmful, ...)"
description: >
  Did you find a project, which shouldn't be on the list anymore? 
  Are you a maintainer of one of the listed projects and want it removed?

title: "Remove <project>"
labels: removal

body:
  - type: input
    id: project
    attributes:
      label: Affected Project
      description: Which project should be removed?
    validations:
      required: true
      
  - type: textarea
    id: reason-for-removal
    attributes:
      label: Reason for removal
      description: Why should this project be removed?
    validations:
      required: true
    